version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    build:
      context: docker/mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - ./data/mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: app
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
        - db  
 